# This is a basic workflow to help you get started with Actions

name: Docker Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2



      - name: Build and push spark
        uses: docker/build-push-action@v3
        with:
          context: ./spark
          file: ./spark/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/spark:latest,jayachander/spark:spark3.2.1

#      - name: Run a docker build hadoop base
#        run: |
#          docker build ./base -t jayachander/hadoop-base:1.0.0-hadoop3.3.2-java8

#      - name: Run a docker push hadoop base
#        run: |
#          docker push jayachander/hadoop-base:1.0.0-hadoop3.3.2-java8
