# This is a basic workflow to help you get started with Actions

name: Docker Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker.DOCKER_USER }}
          password: ${{ secrets.docker.DOCKER_PASSWORD }}

      # Runs a docker build 
      - name: Build and push hadoop base
        #uses: jayachanders/ubuntu-docker-hadoop@v2
        uses: ./
        with:
          context: ./base
          file: ./base/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/hadoop-base:latest,jayachander/hadoop-base:1.0.0-hadoop3.3.2-java8

      - name: Build and push hadoop namenode
        uses: ./
        with:
          context: ./namenode
          file: ./namenode/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/hadoop-namenode:latest,jayachander/hadoop-namenode:1.0.0-hadoop3.3.2-java8

      - name: Build and push hadoop datanode
        uses: ./
        with:
          context: ./datanode
          file: ./datanode/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/hadoop-datanode:latest,jayachander/hadoop-datanode:1.0.0-hadoop3.3.2-java8

      - name: Build and push hadoop resourcemanager
        uses: ./
        with:
          context: ./resourcemanager
          file: ./resourcemanager/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/hadoop-resourcemanager:latest,jayachander/hadoop-resourcemanager:1.0.0-hadoop3.3.2-java8

      - name: Build and push hadoop historyserver
        uses: ./
        with:
          context: ./historyserver
          file: ./historyserver/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/hadoop-historyserver:latest,jayachander/hadoop-historyserver:1.0.0-hadoop3.3.2-java8

      - name: Build and push hadoop nodemanager
        uses: ./
        with:
          context: ./nodemanager
          file: ./nodemanager/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jayachander/hadoop-nodemanager:latest,jayachander/hadoop-nodemanager:1.0.0-hadoop3.3.2-java8

#      - name: Run a docker build hadoop base
#        run: |
#          docker build ./base -t jayachander/hadoop-base:1.0.0-hadoop3.3.2-java8

#      - name: Run a docker push hadoop base
#        run: |
#          docker push jayachander/hadoop-base:1.0.0-hadoop3.3.2-java8
